### ISSUE TITLE
Create documentation template for the repo

### ISSUE THREAD

**Issue by ashishsingh18** [CBICA/NiChart_DLMUSE#9]
Based on github pages

**Comment by georgeaidinis** [comment]
Could you elaborate on this? What needs to be done? Based on which github pages? How should this be done?

**Comment by AlexanderGetka-cbica** [comment]
No worries @georgeaidinis, this will just reflect me creating a basic readthedocs template and writing a workflow in in our CI so that the documentation is accessible on GitHub Pages, which lets you statically host content. Very useful for hosting project-specific docs like this. Once that's done we can put in the usage documentation
